version: '3.8'

services:
  flink-jobmanager:
    image: flink:1.18.0
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    networks:
      - flink-network

  flink-taskmanager:
    image: flink:1.18.0
    depends_on:
      - flink-jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    command: taskmanager
    networks:
      - flink-network
    deploy:
      replicas: 2

  submit-job:
    image: flink:1.18.0
    depends_on:
      - flink-jobmanager
      - flink-taskmanager
    volumes:
      - ./build/libs:/opt/flink/jobs
    command: >
      flink run -m flink-jobmanager:8081
      -c org.example.payment_over_limit.PaymentLimitApp
      /opt/flink/jobs/payment-limit.jar
    networks:
      - flink-network

networks:
  flink-network:
    driver: bridge
